"""Baseline schema: every table in models_pg.py (UPG-16).

Revision ID: 0001_baseline
Revises: (none)
Create Date: 2026-10-10

Generated with `alembic revision --autogenerate` against an empty PostgreSQL
database. It replaces the two earlier incremental migrations (org units and
scoped roles; campuses, buildings, rooms and venue bookings), which assumed the
core tables already existed. A database built by the old start-up code is
brought under Alembic with `alembic stamp 0001_baseline` (docs/DEPLOY.md).
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('event_title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('spoc_email', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_event_id'), 'announcements', ['event_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actorEmail', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('targetId', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coupon_uses',
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('flask_sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flask_sessions_expiry'), 'flask_sessions', ['expiry'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_login_attempts_key_at', 'login_attempts', ['key', 'at'], unique=False)
    op.create_index(op.f('ix_login_attempts_at'), 'login_attempts', ['at'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('logoUrl', sa.String(length=500), nullable=True),
    sa.Column('faviconUrl', sa.String(length=500), nullable=True),
    sa.Column('primaryColor', sa.String(length=20), nullable=True),
    sa.Column('accentColor', sa.String(length=20), nullable=True),
    sa.Column('customDomain', sa.String(length=255), nullable=True),
    sa.Column('apiKey', sa.String(length=128), nullable=True),
    sa.Column('ownerEmail', sa.String(length=255), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('settingsJson', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customDomain')
    )
    op.create_index(op.f('ix_organizations_apiKey'), 'organizations', ['apiKey'], unique=True)
    op.create_index(op.f('ix_organizations_domain'), 'organizations', ['domain'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('payment_orders',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('eventId', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('amountPaise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('couponCode', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paymentId', sa.String(length=128), nullable=True),
    sa.Column('regId', sa.String(length=128), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paidAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('regDataJson', sa.Text(), nullable=True),
    sa.Column('failureReason', sa.Text(), nullable=True),
    sa.Column('refundId', sa.String(length=128), nullable=True),
    sa.Column('refundedAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refundedBy', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paymentId')
    )
    op.create_index(op.f('ix_payment_orders_email'), 'payment_orders', ['email'], unique=False)
    op.create_index(op.f('ix_payment_orders_eventId'), 'payment_orders', ['eventId'], unique=False)
    op.create_table('push_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('userEmail', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('authKey', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_push_subscriptions_userEmail'), 'push_subscriptions', ['userEmail'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('userId', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('scopeType', sa.String(length=50), nullable=False),
    sa.Column('scopeId', sa.String(length=128), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_role_user_scope', 'role_assignments', ['userId', 'scopeType', 'scopeId'], unique=False)
    op.create_index(op.f('ix_role_assignments_scopeId'), 'role_assignments', ['scopeId'], unique=False)
    op.create_index(op.f('ix_role_assignments_userId'), 'role_assignments', ['userId'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('SuperAdmin', 'Coordinator', 'SPOC', 'Judge', 'Participant', 'UniversityAdmin', 'UnitAdmin', 'EventOrganizer', 'EventCoordinator', 'Volunteer', name='userrole'), nullable=False),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('passwordHash', sa.String(length=255), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('campuses',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('organizationId', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campuses_organizationId'), 'campuses', ['organizationId'], unique=False)
    op.create_index(op.f('ix_campuses_slug'), 'campuses', ['slug'], unique=True)
    op.create_table('org_units',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('organizationId', sa.String(length=128), nullable=False),
    sa.Column('parentId', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parentId'], ['org_units.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_units_organizationId'), 'org_units', ['organizationId'], unique=False)
    op.create_index(op.f('ix_org_units_parentId'), 'org_units', ['parentId'], unique=False)
    op.create_index(op.f('ix_org_units_slug'), 'org_units', ['slug'], unique=False)
    op.create_table('buildings',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('campusId', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campusId'], ['campuses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buildings_campusId'), 'buildings', ['campusId'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('buildingId', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('roomNumber', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('facilitiesJson', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['buildingId'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_buildingId'), 'rooms', ['buildingId'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organizationId', sa.String(length=128), nullable=True),
    sa.Column('orgUnitId', sa.String(length=128), nullable=True),
    sa.Column('roomId', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('Technical', 'Cultural', 'Sports', 'Management', name='eventcategory'), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('eventType', sa.String(length=100), nullable=True),
    sa.Column('eventMode', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('startDatetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('endDatetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('venue', sa.String(length=300), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_approval', 'published', 'registration_open', 'registration_closed', 'in_progress', 'evaluation', 'active', 'inactive', 'completed', 'certified', 'cancelled', 'archived', name='eventstatus'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('pricingType', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('maxTeams', sa.Integer(), nullable=True),
    sa.Column('minTeamSize', sa.Integer(), nullable=False),
    sa.Column('maxTeamSize', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('totalRounds', sa.Integer(), nullable=False),
    sa.Column('activeRound', sa.Integer(), nullable=False),
    sa.Column('posterUrl', sa.String(length=500), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('prizes', sa.Text(), nullable=True),
    sa.Column('coordinatorId', sa.String(length=128), nullable=True),
    sa.Column('spoc_id', sa.String(length=255), nullable=True),
    sa.Column('registration_count', sa.Integer(), nullable=False),
    sa.Column('open_hall_mode', sa.Boolean(), nullable=False),
    sa.Column('scoring_locked', sa.Boolean(), nullable=False),
    sa.Column('judging_criteria_json', sa.Text(), nullable=True),
    sa.Column('staff_json', sa.Text(), nullable=True),
    sa.Column('workflowConfigJson', sa.Text(), nullable=True),
    sa.Column('evaluationConfigJson', sa.Text(), nullable=True),
    sa.Column('ticketTiersJson', sa.Text(), nullable=True),
    sa.Column('notificationRulesJson', sa.Text(), nullable=True),
    sa.Column('certificateConfigJson', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['orgUnitId'], ['org_units.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['roomId'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_status_date', 'events', ['status', 'date'], unique=False)
    op.create_index(op.f('ix_events_orgUnitId'), 'events', ['orgUnitId'], unique=False)
    op.create_index(op.f('ix_events_organizationId'), 'events', ['organizationId'], unique=False)
    op.create_index(op.f('ix_events_roomId'), 'events', ['roomId'], unique=False)
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=False)
    op.create_index(op.f('ix_events_spoc_id'), 'events', ['spoc_id'], unique=False)
    op.create_table('event_forms',
    sa.Column('eventId', sa.UUID(), nullable=False),
    sa.Column('fieldsJson', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('eventId')
    )
    op.create_table('event_sessions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('eventId', sa.UUID(), nullable=False),
    sa.Column('trackName', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('speakerName', sa.String(length=200), nullable=True),
    sa.Column('speakerBio', sa.Text(), nullable=True),
    sa.Column('roomNumber', sa.String(length=100), nullable=True),
    sa.Column('startTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_sessions_eventId'), 'event_sessions', ['eventId'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eventId', sa.UUID(), nullable=False),
    sa.Column('leadName', sa.String(length=200), nullable=False),
    sa.Column('leadEmail', sa.String(length=255), nullable=False),
    sa.Column('leadPhone', sa.String(length=20), nullable=False),
    sa.Column('teamName', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'waitlisted', 'checked_in', 'applied', 'pending_payment', 'round_1', 'shortlisted', 'finalist', 'winner', 'runner_up', 'eliminated', 'completed', 'certified', name='registrationstatus'), nullable=False),
    sa.Column('paymentStatus', sa.Enum('unpaid', 'paid', 'waived', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('paymentId', sa.String(length=200), nullable=True),
    sa.Column('attendance', sa.Enum('Present', 'Absent', 'Pending', name='attendancestatus'), nullable=False),
    sa.Column('currentRound', sa.Integer(), nullable=False),
    sa.Column('isEliminated', sa.Boolean(), nullable=False),
    sa.Column('qrCodeUrl', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('assigned_judge_email', sa.String(length=255), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('payment_mode', sa.String(length=100), nullable=True),
    sa.Column('assigned_room', sa.String(length=100), nullable=True),
    sa.Column('checkin_time', sa.String(length=100), nullable=True),
    sa.Column('ticket_id', sa.String(length=128), nullable=True),
    sa.Column('feedback_json', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_registrations_event_attendance_status', 'registrations', ['eventId', 'attendance', 'status'], unique=False)
    op.create_index(op.f('ix_registrations_eventId'), 'registrations', ['eventId'], unique=False)
    op.create_index(op.f('ix_registrations_leadEmail'), 'registrations', ['leadEmail'], unique=False)
    op.create_table('form_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eventId', sa.UUID(), nullable=False),
    sa.Column('registrationId', sa.UUID(), nullable=False),
    sa.Column('answersJson', sa.Text(), nullable=False),
    sa.Column('submittedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrationId'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_submissions_eventId'), 'form_submissions', ['eventId'], unique=False)
    op.create_index(op.f('ix_form_submissions_registrationId'), 'form_submissions', ['registrationId'], unique=False)
    op.create_table('project_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('eventId', sa.UUID(), nullable=False),
    sa.Column('registrationId', sa.UUID(), nullable=False),
    sa.Column('teamName', sa.String(length=200), nullable=False),
    sa.Column('projectTitle', sa.String(length=255), nullable=False),
    sa.Column('tagline', sa.String(length=500), nullable=True),
    sa.Column('problemStatement', sa.Text(), nullable=True),
    sa.Column('solutionOverview', sa.Text(), nullable=True),
    sa.Column('techStack', sa.String(length=500), nullable=True),
    sa.Column('githubUrl', sa.String(length=500), nullable=True),
    sa.Column('demoUrl', sa.String(length=500), nullable=True),
    sa.Column('videoUrl', sa.String(length=500), nullable=True),
    sa.Column('slideDeckUrl', sa.String(length=500), nullable=True),
    sa.Column('milestoneStage', sa.String(length=50), nullable=False),
    sa.Column('scoreImpact', sa.Float(), nullable=True),
    sa.Column('scoreTech', sa.Float(), nullable=True),
    sa.Column('scoreUx', sa.Float(), nullable=True),
    sa.Column('scorePitch', sa.Float(), nullable=True),
    sa.Column('totalScore', sa.Float(), nullable=True),
    sa.Column('submittedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrationId'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_submissions_eventId'), 'project_submissions', ['eventId'], unique=False)
    op.create_index(op.f('ix_project_submissions_registrationId'), 'project_submissions', ['registrationId'], unique=False)
    op.create_table('scores',
    sa.Column('registrationId', sa.UUID(), nullable=False),
    sa.Column('judgeId', sa.String(length=128), nullable=False),
    sa.Column('judgeName', sa.String(length=200), nullable=True),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('scoredAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['registrationId'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('registrationId', 'judgeId')
    )
    op.create_table('team_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registrationId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('usn', sa.String(length=50), nullable=True),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['registrationId'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_registrationId'), 'team_members', ['registrationId'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('eventId', sa.UUID(), nullable=False),
    sa.Column('registrationId', sa.UUID(), nullable=False),
    sa.Column('userEmail', sa.String(length=255), nullable=False),
    sa.Column('ticketType', sa.String(length=100), nullable=False),
    sa.Column('ticketCode', sa.String(length=100), nullable=False),
    sa.Column('qrTokenHash', sa.String(length=255), nullable=False),
    sa.Column('gateAssignment', sa.String(length=100), nullable=True),
    sa.Column('seatAssignment', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('checkedInAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrationId'], ['registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_eventId'), 'tickets', ['eventId'], unique=False)
    op.create_index(op.f('ix_tickets_registrationId'), 'tickets', ['registrationId'], unique=False)
    op.create_index(op.f('ix_tickets_ticketCode'), 'tickets', ['ticketCode'], unique=True)
    op.create_index(op.f('ix_tickets_userEmail'), 'tickets', ['userEmail'], unique=False)
    op.create_table('venue_bookings',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('roomId', sa.String(length=128), nullable=False),
    sa.Column('eventId', sa.UUID(), nullable=True),
    sa.Column('sessionId', sa.String(length=128), nullable=True),
    sa.Column('startTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('endTime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['eventId'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roomId'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sessionId'], ['event_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_venue_bookings_room_time', 'venue_bookings', ['roomId', 'startTime', 'endTime', 'status'], unique=False)
    op.create_index(op.f('ix_venue_bookings_eventId'), 'venue_bookings', ['eventId'], unique=False)
    op.create_index(op.f('ix_venue_bookings_roomId'), 'venue_bookings', ['roomId'], unique=False)
    op.create_index(op.f('ix_venue_bookings_sessionId'), 'venue_bookings', ['sessionId'], unique=False)
    # ### end Alembic commands ###


ENUM_TYPES = ('userrole', 'eventcategory', 'eventstatus', 'registrationstatus',
              'paymentstatus', 'attendancestatus')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_bookings_sessionId'), table_name='venue_bookings')
    op.drop_index(op.f('ix_venue_bookings_roomId'), table_name='venue_bookings')
    op.drop_index(op.f('ix_venue_bookings_eventId'), table_name='venue_bookings')
    op.drop_index('idx_venue_bookings_room_time', table_name='venue_bookings')
    op.drop_table('venue_bookings')
    op.drop_index(op.f('ix_tickets_userEmail'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_ticketCode'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_registrationId'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_eventId'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_team_members_registrationId'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_table('scores')
    op.drop_index(op.f('ix_project_submissions_registrationId'), table_name='project_submissions')
    op.drop_index(op.f('ix_project_submissions_eventId'), table_name='project_submissions')
    op.drop_table('project_submissions')
    op.drop_index(op.f('ix_form_submissions_registrationId'), table_name='form_submissions')
    op.drop_index(op.f('ix_form_submissions_eventId'), table_name='form_submissions')
    op.drop_table('form_submissions')
    op.drop_index(op.f('ix_registrations_leadEmail'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_eventId'), table_name='registrations')
    op.drop_index('idx_registrations_event_attendance_status', table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_event_sessions_eventId'), table_name='event_sessions')
    op.drop_table('event_sessions')
    op.drop_table('event_forms')
    op.drop_index(op.f('ix_events_spoc_id'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_index(op.f('ix_events_roomId'), table_name='events')
    op.drop_index(op.f('ix_events_organizationId'), table_name='events')
    op.drop_index(op.f('ix_events_orgUnitId'), table_name='events')
    op.drop_index('idx_events_status_date', table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_rooms_buildingId'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_buildings_campusId'), table_name='buildings')
    op.drop_table('buildings')
    op.drop_index(op.f('ix_org_units_slug'), table_name='org_units')
    op.drop_index(op.f('ix_org_units_parentId'), table_name='org_units')
    op.drop_index(op.f('ix_org_units_organizationId'), table_name='org_units')
    op.drop_table('org_units')
    op.drop_index(op.f('ix_campuses_slug'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_organizationId'), table_name='campuses')
    op.drop_table('campuses')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_role_assignments_userId'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_scopeId'), table_name='role_assignments')
    op.drop_index('idx_role_user_scope', table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_push_subscriptions_userEmail'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')
    op.drop_index(op.f('ix_payment_orders_eventId'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_email'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_domain'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_apiKey'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_login_attempts_at'), table_name='login_attempts')
    op.drop_index('idx_login_attempts_key_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_flask_sessions_expiry'), table_name='flask_sessions')
    op.drop_table('flask_sessions')
    op.drop_table('coupon_uses')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_announcements_event_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
    # PostgreSQL keeps enum types after their tables are dropped.
    if op.get_bind().dialect.name == 'postgresql':
        for name in ENUM_TYPES:
            op.execute(f'DROP TYPE IF EXISTS {name}')
